# Generated by Django 3.1 on 2020-08-16 09:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mortgage', models.IntegerField(default=0)),
                ('vaad_bayit', models.IntegerField(default=0)),
                ('internet_tel', models.IntegerField(default=0)),
                ('cell_phone', models.IntegerField(default=0)),
                ('life_insurance', models.IntegerField(default=0)),
                ('health_insurance', models.IntegerField(default=0)),
                ('home_insurance', models.IntegerField(default=0)),
                ('therapy', models.IntegerField(default=0)),
                ('tuters', models.IntegerField(default=0)),
                ('children_savings', models.IntegerField(default=0)),
                ('bank_fees', models.IntegerField(default=0)),
                ('monthly_loan', models.IntegerField(default=0)),
                ('charity', models.IntegerField(default=0)),
                ('car_insurance_chova', models.IntegerField(default=0)),
                ('car_insurance_makif', models.IntegerField(default=0)),
                ('extracurricular_activity', models.IntegerField(default=0)),
                ('tuition', models.IntegerField(default=0)),
                ('kids_transportation', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly', models.IntegerField(default=0)),
                ('extra_days', models.IntegerField(default=0)),
                ('transportation', models.IntegerField(default=0)),
                ('cleaning_help', models.IntegerField(default=0)),
                ('gas', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Annual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_tax', models.IntegerField(default=0)),
                ('water', models.IntegerField(default=0)),
                ('gas', models.IntegerField(default=0)),
                ('electric', models.IntegerField(default=0)),
                ('holidays', models.IntegerField(default=0)),
                ('dental', models.IntegerField(default=0)),
                ('eyecare', models.IntegerField(default=0)),
                ('alternative_medicine', models.IntegerField(default=0)),
                ('kids_gifts', models.IntegerField(default=0)),
                ('couples_gifts', models.IntegerField(default=0)),
                ('general_gifts', models.IntegerField(default=0)),
                ('school_supplies', models.IntegerField(default=0)),
                ('membership_fees', models.IntegerField(default=0)),
                ('day_trips', models.IntegerField(default=0)),
                ('couples_vacation', models.IntegerField(default=0)),
                ('family_vacation', models.IntegerField(default=0)),
                ('car_registration', models.IntegerField(default=0)),
                ('car_test', models.IntegerField(default=0)),
                ('car_repairs', models.IntegerField(default=0)),
                ('extracurricular_activity', models.IntegerField(default=0)),
                ('water_filter', models.IntegerField(default=0)),
                ('extra_income', models.IntegerField(default=0)),
                ('other_school_fees', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
