# Generated by Django 3.1 on 2020-09-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='approved',
            field=models.CharField(default='approved', max_length=30),
        ),
    ]
