# Generated by Django 3.1 on 2020-08-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_moneyspent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyspent',
            name='spent',
            field=models.IntegerField(null=True),
        ),
    ]
