# Generated by Django 3.1 on 2020-09-16 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_expenses_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='approved',
            new_name='status',
        ),
    ]
