# Generated by Django 3.1 on 2020-08-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20200818_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyspent',
            name='spent',
            field=models.IntegerField(default=0),
        ),
    ]
