# Generated by Django 3.1 on 2020-09-29 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_botexpensebalance_botexpenseinput_botunexpectedexpense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botexpensebalance',
            old_name='text',
            new_name='eb_text',
        ),
        migrations.RenameField(
            model_name='botexpenseinput',
            old_name='text',
            new_name='ei_text',
        ),
        migrations.RenameField(
            model_name='botunexpectedexpense',
            old_name='text',
            new_name='ue_text',
        ),
    ]
