# Generated by Django 3.1 on 2020-09-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_expenses',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='annual',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='moneyspent',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='monthly',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
