# Generated by Django 3.1 on 2020-09-02 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_auto_20200902_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 2, 14, 42, 31, 887445, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='annual',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 2, 14, 42, 31, 887016, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 2, 14, 42, 31, 888058, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='daily',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 2, 14, 42, 31, 885977, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='moneyspent',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 2, 14, 42, 31, 887749, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='monthly',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 2, 14, 42, 31, 886423, tzinfo=utc)),
        ),
    ]
