# Generated by Django 3.1 on 2020-09-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_auto_20200902_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyspent',
            name='name',
            field=models.CharField(default='expense', max_length=100),
        ),
    ]
