# Generated by Django 3.1 on 2020-09-02 14:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calspending',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 2, 14, 39, 37, 158890, tzinfo=utc)),
        ),
    ]
