# Generated by Django 3.1 on 2020-09-02 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_auto_20200902_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calspending',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 2, 14, 42, 31, 888876, tzinfo=utc)),
        ),
    ]
