# Generated by Django 3.1 on 2020-09-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_auto_20200902_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalSpending',
        ),
    ]
